version: '1'
services:
  nextjs-fullstack:
    image: node:20
    command: bash -c "cd /app && yarn && yarn dev"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image:
    restart:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: njfs
    volumes:
      - db-data:/var/lib/postgresql/data
  volumes:
    db-data: